export default function Head() {
  return (
    <>
      <title>Jeoffrey-Rico-Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/JR_logo_RTRI.svg/512px-JR_logo_RTRI.svg.png" />
    </>
  )
}
